$includes

#ifdef __cplusplus
extern "C" {
void setup();
void loop();
}
#endif

//----------------------------------------------------------------------
// User defined event handlers
$handlers
// End of user defined event handlers
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Non-public area
namespace $privateNamespace {
$privateObjects
}
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Component views (public objects)
$publicObjects
// End of component views (public objects)
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// EEPROM items (public objects)
$eepromData
// End of EEPROM items (public objects)
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Initialization of EEPROM data
namespace $privateNamespace {
void initializeEeprom() {
$eepromDataInitialization
}
}
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Method wrappers
namespace $privateNamespace {
$methodWrappersSection
}
//----------------------------------------------------------------------

$loopersSection

// Autogenerated setup
void setup() {
$setup
}

// Autogenerated loop
void loop() {
$loop
}
