$includes

#ifdef __cplusplus
extern "C" {
void setup();
void loop();
}
#endif

//----------------------------------------------------------------------
// User defined event handlers
$handlers
// End of user defined event handlers
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Non-public area
namespace $privateNamespace {
$privateObjects
}
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Component views (public objects)
$publicObjects
// End of component views (public objects)
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Eeprom variables (public objects)
$eepromVars
// End of eeprom variables (public objects)
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Initialization of eeprom variables
namespace $privateNamespace {
void initializeEepromVars() {
$eepromVarsInitialization
}
}
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Method wrappers
namespace $privateNamespace {
$methodWrappersSection
}
//----------------------------------------------------------------------

$loopersSection

// Autogenerated setup
void setup() {
$setup
}

// Autogenerated loop
void loop() {
$loop
}
